USE QUANLYGIANGVIEN
GO
-- START NHAP GIANGVIEN --
	CREATE PROCEDURE SP_NHAPGIANGVIEN
	@MAGV NVARCHAR(20), 
	@HOTEN NVARCHAR(50), 
	@DIACHI NVARCHAR(100),
	@DIENTHOAI NVARCHAR(14),
	@MAKHOA NVARCHAR(20)
	AS
	BEGIN
		INSERT INTO GIANGVIEN(MAGV, HOTEN, DIACHI, DIENTHOAI, MAKHOA)
		VALUES(@MAGV, @HOTEN, @DIACHI, @DIENTHOAI, @MAKHOA)
	END
	-- START TEST --
		EXEC SP_NHAPGIANGVIEN N'013T3K21', N'Trần Nguyễn Tuấn Anh', N'Lâm Đồng', N'0325555077', N'CNTT'
	-- END TEST --
-- END NHAP GIANGVIEN --

-- START CHECK GIANG VIEN --
	CREATE PROCEDURE SP_CHECKGIANGVIEN
	@MAGV NVARCHAR(20)
	AS
	BEGIN
		SELECT MAGV AS N'Mã Giảng Viên', HOTEN AS N'Tên Giảng Viên', DIACHI AS N'Địa Chỉ', DIENTHOAI AS N'Điện Thoại', MAKHOA AS N'Mã Khoa'
		FROM GIANGVIEN
		WHERE MAGV=@MAGV
	END
	-- START TEST --
		EXEC SP_CHECKGIANGVIEN N'013T3K21'
	-- END TEST --
-- END CHECK GIANG VIEN --

-- START XEM GIANGVIEN --
	CREATE PROCEDURE SP_XEMGIANGVIEN
	AS
	BEGIN
		SELECT MAGV AS N'Mã Giảng Viên', HOTEN AS N'Tên Giảng Viên', DIACHI AS N'Địa Chỉ', DIENTHOAI AS N'Điện Thoại', MAKHOA AS N'Mã Khoa'
		FROM GIANGVIEN
	END
	-- START TEST --
		EXEC SP_XEMGIANGVIEN
	-- END TEST --
-- END XEM GIANGVIEN --

-- START XOA GIANGVIEN --
	CREATE PROCEDURE SP_XOAGIANGVIEN
	@MAGV NVARCHAR(20)
	AS
	BEGIN
		DELETE
		FROM GIANGVIEN
		WHERE MAGV=@MAGV
	END
	-- START TEST --
		EXEC SP_XOAGIANGVIEN N'013T3K21'
	-- END TEST --
-- END XOA GIANGVIEN --

-- START TIM GIANGVIEN --
	CREATE PROCEDURE SP_TIMGIANGVIEN
	@MAGV NVARCHAR(20), 
	@HOTEN NVARCHAR(50), 
	@DIACHI NVARCHAR(100),
	@DIENTHOAI NVARCHAR(14),
	@MAKHOA NVARCHAR(20)
	AS
	BEGIN
		SELECT MAGV AS N'Mã Giảng Viên', HOTEN AS N'Tên Giảng Viên', DIACHI AS N'Địa Chỉ', DIENTHOAI AS N'Điện Thoại', MAKHOA AS N'Mã Khoa'
		FROM GIANGVIEN
		WHERE MAGV=@MAGV OR
			  HOTEN=@HOTEN OR
			  DIACHI=@DIACHI OR
			  DIENTHOAI=@DIACHI OR
			  MAKHOA=@MAKHOA
	END
	-- START TEST --
		EXEC SP_TIMGIANGVIEN N'013T3K21', N'', N'', N'', N''
	-- END TEST --
-- END TIM GIANGVIEN --

-- START CAP NHAT GIANGVIEN --
	CREATE PROCEDURE SP_CAPNHATGIANGVIEN
	@MAGVCU NVARCHAR(20) = '', 
	@HOTENMOI NVARCHAR(50) = '', 
	@DIACHIMOI NVARCHAR(100) = '',
	@DIENTHOAIMOI NVARCHAR(14) = '',
	@MAKHOAMOI NVARCHAR(20) = ''
	AS
	BEGIN
		UPDATE GIANGVIEN
			SET HOTEN=@HOTENMOI,
				DIACHI=@DIACHIMOI,
				DIENTHOAI=@DIENTHOAIMOI,
				MAKHOA=@MAKHOAMOI
		WHERE MAGV=@MAGVCU
	END
	-- START TEST --
		EXEC SP_CAPNHATGIANGVIEN N'013T3K21', N'Trần Nguyễn Tuấn Anh', N'Đà Lạt', N'0325555077', N'CNTT'
	-- END TEST --
-- END CAP NHAT GIANGVIEN --