USE QUANLYGIANGVIEN
GO
-- START NHAP MONHOC --
	CREATE PROCEDURE SP_NHAPMONHOC
	@MAMH NVARCHAR(20), 
	@TENMH NVARCHAR(50), 
	@SOTIET TINYINT,
	@MAKHOA NVARCHAR(20)
	AS
	BEGIN
		INSERT INTO MONHOC(MAMH, TENMH, SOTIET, MAKHOA)
		VALUES(@MAMH, @TENMH, @SOTIET, @MAKHOA)
	END
	-- START TEST --
		EXEC SP_NHAPMONHOC N'LRBT', N'Lắp Ráp Bảo Trì', N'45', N'CNTT'
	-- END TEST --
-- END NHAP MONHOC --

-- START CHECK MON HOC --
	CREATE PROCEDURE SP_CHECKMONHOC
		@MAMH NVARCHAR(20)
		AS
		BEGIN
			SELECT MAMH AS N'Mã Môn Học', TENMH AS N'Tên Môn Học', SOTIET AS N'Số Tiết', MAKHOA AS N'Mã Khoa'
			FROM MONHOC
			WHERE MAMH=@MAMH
		END
		-- START TEST --
		EXEC SP_CHECKMONHOC N'LRBT'
		-- END TEST --
-- END CHECK MON HOC --

-- START XEM MONHOC --
	CREATE PROCEDURE SP_XEMMONHOC
	AS
	BEGIN
		SELECT MAMH AS N'Mã Môn Học', TENMH AS N'Tên Môn Học', SOTIET AS N'Số Tiết', MAKHOA AS N'Mã Khoa'
		FROM MONHOC
	END
	-- START TEST --
		EXEC SP_XEMMONHOC
	-- END TEST --
-- END XEM MONHOC --

-- START XOA MONHOC --
	CREATE PROCEDURE SP_XOAMONHOC
	@MAMH NVARCHAR(20)
	AS
	BEGIN
		DELETE
		FROM MONHOC
		WHERE MAMH=@MAMH
	END
	-- START TEST --
		EXEC SP_XOAMONHOC N'LRBT'
	-- END TEST --
-- END XOA MONHOC --

-- START TIM MONHOC --
	CREATE PROCEDURE SP_TIMMONHOC
	@MAMH NVARCHAR(20), 
	@TENMH NVARCHAR(50), 
	@SOTIET TINYINT,
	@MAKHOA NVARCHAR(20)
	AS
	BEGIN
		SELECT MAMH AS N'Mã Môn Học', TENMH AS N'Tên Môn Học', SOTIET AS N'Số Tiết', MAKHOA AS N'Mã Khoa'
		FROM MONHOC
		WHERE MAMH=@MAMH OR
			TENMH=@TENMH OR
			SOTIET=@SOTIET OR
			MAKHOA=@MAKHOA
	END
	-- START TEST --
		EXEC SP_TIMMONHOC N'LRBT', N'', N'', N''
	-- END TEST --
-- END TIM MONHOC --

-- START CAP NHAT MONHOC --
	CREATE PROCEDURE SP_CAPNHATMONHOC
		@MAMMHCU NVARCHAR(20) = '',
		@TENMHMOI NVARCHAR(50) = '',
		@SOTIETMOI TINYINT = '',
		@MAKHOA NVARCHAR(20)
	AS
	BEGIN
		UPDATE MONHOC
			SET TENMH=@TENMHMOI,
				SOTIET=@SOTIETMOI,
				MAKHOA=@MAKHOA
		WHERE MAMH=@MAMMHCU
	END
	-- START TEST --
		EXEC SP_CAPNHATMONHOC N'LRBT', N'Đồ Họa 3D', N'53', N'CNTT'
	-- END TEST --
-- END CAP NHAT MONHOC --