USE QUANLYGIANGVIEN
GO
-- START NHAP KHOA --
	CREATE PROCEDURE SP_NHAPKHOA
	@MAKHOA NVARCHAR(20), 
	@TENKHOA NVARCHAR(50), 
	@DIENTHOAI NVARCHAR(14)
	AS
	BEGIN
		INSERT INTO KHOA(MAKHOA, TENKHOA, DIENTHOAI)
		VALUES(@MAKHOA, @TENKHOA, @DIENTHOAI)
	END
	-- START TEST --
		EXEC SP_NHAPKHOA N'THCB', N'Tin Học Cơ Bản', N'0325555077'
	-- END TEST --
-- END NHAP KHOA --

-- START CHECK KHOA --
	CREATE PROCEDURE SP_CHECKKHOA
		@MAKHOA NVARCHAR(20)
		AS
		BEGIN
			SELECT MAKHOA AS N'Mã Khoa', TENKHOA AS N'Tên Khoa', DIENTHOAI AS N'Điện Thoại'
			FROM KHOA
			WHERE MAKHOA=@MAKHOA
		END
		-- START TEST --
			EXEC SP_CHECKKHOA
		-- END CHECK KHOA --
-- END CHECK KHOA --

-- START XEM KHOA --
	CREATE PROCEDURE SP_XEMKHOA
	AS
	BEGIN
		SELECT MAKHOA AS N'Mã Khoa', TENKHOA AS N'Tên Khoa', DIENTHOAI AS N'Điện Thoại'
		FROM KHOA
	END
	-- START TEST --
		EXEC SP_XEMKHOA
	-- END TEST --
-- END XEM KHOA --

-- START XOA KHOA --
	CREATE PROCEDURE SP_XOAKHOA
	@MAKHOA NVARCHAR(20)
	AS
	BEGIN
		DELETE
		FROM KHOA
		WHERE MAKHOA=@MAKHOA
	END
	-- START TEST --
		EXEC SP_XOAKHOA N'THCB'
	-- END TEST --
-- END XOA KHOA --

-- START TIM KHOA --
	CREATE PROCEDURE SP_TIMKHOA
	@MAKHOA NVARCHAR(20), 
	@TENKHOA NVARCHAR(50), 
	@DIENTHOAI NVARCHAR(14)
	AS
	BEGIN
		SELECT MAKHOA AS N'Mã Khoa', TENKHOA AS N'Tên Khoa', DIENTHOAI AS N'Điện Thoại'
		FROM KHOA
		WHERE MAKHOA=@MAKHOA OR
			TENKHOA=@TENKHOA OR
			DIENTHOAI=@DIENTHOAI
	END
	-- START TEST --
		EXEC SP_TIMKHOA N'THCB', N'Tin Học Cơ Bản', N'0325555077'
	-- END TEST --
-- END TIM KHOA --

-- START CAP NHAT KHOA --
	CREATE PROCEDURE SP_CAPNHATKHOA
		@MAKHOACU NVARCHAR(20) = '',
		@TENKHOAMOI NVARCHAR(50) = '',
		@DIENTHOAIMOI NVARCHAR(14) = ''
	AS
	BEGIN
		UPDATE KHOA
			SET TENKHOA=@TENKHOAMOI,
				DIENTHOAI=@DIENTHOAIMOI
		WHERE MAKHOA=@MAKHOACU
	END
	-- START TEST --
		EXEC SP_CAPNHATKHOA N'THCB', N'KTHCB', N'0325555077'
	-- END TEST --
-- END CAP NHAT KHOA --