USE master
GO
IF exists (SELECT * FROM sysdatabases WHERE name= 'QUANLYGIANGVIEN')
DROP DATABASE QUANLYGIANGVIEN
GO
CREATE DATABASE QUANLYGIANGVIEN
GO
USE QUANLYGIANGVIEN
GO
CREATE TABLE KHOA
(
	MAKHOA NVARCHAR(20) NOT NULL,
	TENKHOA NVARCHAR(50) NOT NULL,
	DIENTHOAI NVARCHAR(14),
	CONSTRAINT PK_MAKHOA PRIMARY KEY(MAKHOA)
);
GO
CREATE TABLE GIANGVIEN
(
	MAGV NVARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	DIENTHOAI NVARCHAR(14),
	MAKHOA NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_MAGV PRIMARY KEY(MAGV),
	CONSTRAINT FK_GIANGVIEN FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
GO
CREATE TABLE MONHOC
(
	MAMH NVARCHAR(20) NOT NULL,
	TENMH NVARCHAR(50) NOT NULL,
	SOTIET TINYINT NOT NULL,
	MAKHOA NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_MAMH PRIMARY KEY(MAMH),
	CONSTRAINT FK_MONHOC FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);